### ISSUE TITLE
Let's make it responsive

### ISSUE THREAD

**Issue by davisshaver** [coralproject/talk-wp-plugin#9]
CORS is the blocker here... maybe we need to add a postMessage that communicates a height based on window width?

**Comment by davisshaver** [comment]
Whoops there is `pym.js` setup in the repo, I think this is just a generous min-height setting that can be overridden like so: 

```css
.talk-stream-tab-container {
  min-height: unset !important;
}

body {
  padding-bottom: 80px !important;
}
```
